version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 79678130


  # Adminer UI to manage DB
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
