version: '3.8'

services:
  blog-app:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/blogdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=yourpassword
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
